package app.kairo.reader.ui.rsvp

import androidx.compose.ui.unit.dp
import app.kairo.reader.core.model.RsvpFontFamily
import app.kairo.reader.core.model.RsvpFontWeight
import app.kairo.reader.core.rsvp.RsvpSpeedControl

const val DEFAULT_FONT_SIZE_SP = 44f
val DEFAULT_FONT_FAMILY = RsvpFontFamily.INTER
val DEFAULT_FONT_WEIGHT = RsvpFontWeight.LIGHT
const val DEFAULT_TEXT_BRIGHTNESS = 0.88f
const val DEFAULT_VERTICAL_BIAS = -0.15f
const val DEFAULT_HORIZONTAL_BIAS = 0f

const val SAFE_MIN_TEMPO_MS_PER_WORD = RsvpSpeedControl.SAFE_MIN_TEMPO_MS_PER_WORD
const val EXTREME_MIN_TEMPO_MS_PER_WORD = RsvpSpeedControl.EXTREME_MIN_TEMPO_MS_PER_WORD
const val MAX_TEMPO_MS_PER_WORD = RsvpSpeedControl.MAX_TEMPO_MS_PER_WORD
const val DEFAULT_TEMPO_SCALE = 1.0
const val TEMPO_SCALE_MIN = 0.1
const val TEMPO_SCALE_MAX = 4.0
const val MIN_FRAME_DELAY_MS = 16L
const val POSITION_SAVE_INTERVAL_MS = 750L
const val TEMPO_STEP_MS = 5L
const val SPEED_STEP_PERCENT = 2f
const val TEMPO_SWIPE_THRESHOLD_PX = 30f
const val DRAG_AXIS_LOCK_THRESHOLD_PX = 12f
const val SWEEP_SWIPE_THRESHOLD_PX = 30f
const val SWEEP_FRAME_STEP = 1
const val POSITIONING_BIAS_PER_PX = 0.0015f

const val LOADING_TEXT_ALPHA = 0.6f
const val PROGRESS_PRIMARY_ALPHA = 0.7f
const val PROGRESS_TRACK_ALPHA = 0.18f
const val TOP_BAR_ICON_ALPHA = 0.54f
const val TOP_BAR_BUTTON_BACKGROUND_ALPHA = 0.18f
const val TOP_BAR_BUTTON_BORDER_ALPHA = 0.08f
const val INDICATOR_BACKGROUND_ALPHA = 0.9f
const val QUICK_SETTINGS_BACKGROUND_ALPHA = 0.97f
const val QUICK_SETTINGS_BORDER_ALPHA = 0.18f
const val QUICK_SETTINGS_HANDLE_ALPHA = 0.42f
const val CONTROLS_BACKGROUND_ALPHA = 0.72f
const val CONTROLS_BORDER_ALPHA = 0.10f
const val CONTROLS_PILL_BACKGROUND_ALPHA = 0.34f
const val CONTROLS_PILL_LABEL_ALPHA = 0.48f
const val CONTROLS_PILL_VALUE_ALPHA = 0.78f
const val POSITIONING_LINE_ALPHA = 0.10f
const val PROGRESS_TEXT_ALPHA = 0.6f
const val RESUME_TEXT_ALPHA = 0.4f
const val PARAGRAPH_TEXT_ALPHA = 0.66f
const val PARAGRAPH_COMPACT_TEXT_ALPHA = 0.76f
const val PARAGRAPH_COMPACT_HIGHLIGHT_ALPHA = 1.0f
const val PARAGRAPH_COMPACT_HIGHLIGHT_BACKGROUND_ALPHA = 0.18f
const val PARAGRAPH_OFFSET_MULTIPLIER = 3.6f
const val PARAGRAPH_FONT_SCALE = 0.5f
const val PARAGRAPH_COMPACT_FONT_SCALE = 0.62f
const val MIN_PARAGRAPH_FONT_SIZE_SP = 14f
const val MAX_PARAGRAPH_FONT_SIZE_SP = 22f
const val MAX_PARAGRAPH_COMPACT_FONT_SIZE_SP = 28f
const val PARAGRAPH_LINE_HEIGHT_MULTIPLIER = 1.45f
const val PARAGRAPH_PREVIEW_WINDOW_WORDS = 58
const val PARAGRAPH_COMPACT_PREVIEW_WINDOW_WORDS = 14
const val PARAGRAPH_COMPACT_PREVIEW_HIGHLIGHT_FRACTION = 0.35f
const val COMPACT_PREVIEW_SNAP_MIN_LINES = 2.4f

const val TEXT_BRIGHTNESS_MIN = 0.55f
const val TEXT_BRIGHTNESS_MAX = 1.0f
const val PIVOT_LINE_ALPHA_BASE = 0.06f
const val PIVOT_LINE_ALPHA_MIN = 0f
const val PIVOT_LINE_ALPHA_MAX = 1f

const val VERTICAL_BIAS_MIN = -0.7f
const val VERTICAL_BIAS_MAX = 0.7f
const val HORIZONTAL_BIAS_MIN = -0.6f
const val HORIZONTAL_BIAS_MAX = 0.6f

const val MIN_FONT_SIZE_SP = 28f
const val MAX_FONT_SIZE_SP = 80f

const val CONTROLS_HIDE_DELAY_MS = 3000L
const val TEMPO_INDICATOR_HIDE_DELAY_MS = 1500L
const val FONT_SIZE_INDICATOR_HIDE_DELAY_MS = 1500L

const val MS_PER_MINUTE = 60_000.0
const val MIN_WORD_COUNT = 1
const val MIN_TOTAL_MS = 1L

const val DEFAULT_PIVOT_INDEX = 0
const val INVALID_INDEX = -1
const val ORP_LOCK_PIVOT_WORDS = 1
const val ORP_LETTER_SPACING_SP = 0.5f
const val ORP_GUIDE_BRIGHTNESS_MIN = 0.25f
const val ORP_GUIDE_BRIGHTNESS_MAX = 2.0f
const val ORP_GUIDE_THICKNESS_MIN = 0.5f
const val ORP_GUIDE_THICKNESS_MAX = 3.0f
const val ORP_BIAS_FRACTION_MIN = 0.05f
const val ORP_BIAS_FRACTION_MAX = 0.95f
const val ORP_EDGE_FRACTION_MIN = 0.05f
const val ORP_EDGE_FRACTION_MAX = 0.45f
const val ORP_CENTER_FRACTION = 0.5f
const val ORP_TRANSFORM_ORIGIN_X = 0f
const val ORP_TRANSFORM_ORIGIN_Y = 0.5f
const val MIN_ORP_WIDTH_PX = 1f
const val ORP_MIN_AUTO_FIT_SCALE = 0.72f
const val ORP_ELLIPSIS = '\u2026'

const val ZERO_FLOAT = 0f
const val ONE_FLOAT = 1f
const val CENTER_BIAS = 0f
const val BIAS_SCALE_FACTOR = 2f

val PROGRESS_HEIGHT = 4.dp
val PROGRESS_HORIZONTAL_PADDING = 16.dp
val PROGRESS_BOTTOM_PADDING = 10.dp
val PROGRESS_CORNER_RADIUS = 8.dp
val TOP_BAR_PADDING = 16.dp
val TOP_BAR_SPACING = 8.dp
val TOP_BAR_BUTTON_SIZE = 40.dp
val TOP_BAR_ICON_SIZE = 22.dp
val TEMPO_INDICATOR_TOP_PADDING = 60.dp
val FONT_SIZE_INDICATOR_TOP_PADDING = 112.dp
val INDICATOR_CORNER_RADIUS = 8.dp
val INDICATOR_PADDING_HORIZONTAL = 16.dp
val INDICATOR_PADDING_VERTICAL = 8.dp
val POSITIONING_INDICATOR_PADDING_HORIZONTAL = 14.dp
val POSITIONING_INDICATOR_PADDING_VERTICAL = 8.dp
val QUICK_SETTINGS_CORNER = 8.dp
val QUICK_SETTINGS_MAX_WIDTH = 640.dp
val QUICK_SETTINGS_OUTER_PADDING = 8.dp
val QUICK_SETTINGS_HANDLE_WIDTH = 44.dp
val QUICK_SETTINGS_HANDLE_HEIGHT = 4.dp
val QUICK_SETTINGS_HANDLE_BOTTOM_PADDING = 2.dp
val QUICK_SETTINGS_HORIZONTAL_PADDING = 16.dp
val QUICK_SETTINGS_VERTICAL_PADDING = 14.dp
val QUICK_SETTINGS_SPACING = 12.dp
const val QUICK_SETTINGS_HEIGHT_FRACTION = 0.85f
val POSITION_GUIDE_HEIGHT = 1.dp
val PARAGRAPH_PREVIEW_HORIZONTAL_PADDING = 20.dp
const val PARAGRAPH_FADE_STRONG_ALPHA = 0.58f
const val PARAGRAPH_FADE_MID_ALPHA = 0.45f
const val PARAGRAPH_FADE_SOFT_ALPHA = 0.2f
const val PARAGRAPH_PREVIEW_SURFACE_ALPHA = 0.11f
val PARAGRAPH_PREVIEW_HEIGHT = 224.dp
val PARAGRAPH_FADE_HEIGHT = 64.dp
val PARAGRAPH_PREVIEW_MAX_WIDTH = 560.dp
val PARAGRAPH_PREVIEW_CORNER_RADIUS = 8.dp
val PARAGRAPH_PREVIEW_MIN_ORP_CLEARANCE = 36.dp
val PARAGRAPH_PREVIEW_COMPACT_ORP_OVERLAP = 8.dp
val PARAGRAPH_PREVIEW_COMPACT_TEXT_ORP_CLEARANCE = 28.dp
val PARAGRAPH_PREVIEW_EDGE_PADDING = 20.dp
val PARAGRAPH_PREVIEW_COMPACT_EDGE_PADDING = 12.dp
val PARAGRAPH_PREVIEW_ORP_COLLISION_GAP = 28.dp
val PARAGRAPH_PREVIEW_SWITCH_HYSTERESIS = 18.dp
val PARAGRAPH_PREVIEW_SWITCH_OVERLAP_THRESHOLD = 8.dp
const val ORP_COLLISION_TEXT_HEIGHT_MULTIPLIER = 1.15f
val PARAGRAPH_PREVIEW_CONTENT_PADDING_HORIZONTAL = 16.dp
val PARAGRAPH_PREVIEW_CONTENT_PADDING_VERTICAL = 12.dp

val CONTROLS_PADDING = 18.dp
val CONTROLS_SPACER = 10.dp
val CONTROLS_HINT_SPACER = 4.dp
val CONTROLS_ROW_SPACING = 28.dp
val CONTROLS_MAX_WIDTH = 640.dp
const val CONTROLS_WIDTH_FRACTION = 0.92f
val CONTROLS_OUTER_PADDING = 12.dp
val CONTROLS_CORNER_RADIUS = 8.dp
val CONTROLS_PROGRESS_HEIGHT = 4.dp
val CONTROLS_PROGRESS_CORNER_RADIUS = 8.dp
const val CONTROLS_COLLISION_VERTICAL_BIAS = 0.28f
val CONTROLS_INFO_SPACING = 8.dp
val CONTROLS_INFO_PILL_PADDING_HORIZONTAL = 12.dp
val CONTROLS_INFO_PILL_PADDING_VERTICAL = 8.dp
val CONTROLS_INFO_PILL_CORNER_RADIUS = 8.dp
val SKIP_ICON_SIZE = 32.dp
val PLAY_BUTTON_SIZE = 64.dp
val PLAY_ICON_SIZE = 36.dp
val CONTROLS_RESERVED_HEIGHT = 172.dp
val CONTROLS_COMPACT_RESERVED_HEIGHT = 132.dp

val ORP_HORIZONTAL_PADDING = 8.dp
val ORP_BASE_EDGE = 24.dp
val ORP_EXTRA_EDGE = 14.dp
val ORP_LINE_HEIGHT = 1.dp
val ORP_POINTER_HEIGHT = 12.dp
val ORP_POINTER_WIDTH = 1.dp
val ORP_TEXT_SPACER = 4.dp
val ORP_OPENING_PUNCTUATION = setOf('(', '[', '{', '\u201C', '\u2018')
